### ISSUE TITLE
les

### ISSUE THREAD

**Issue by aru-xyz** [MiafJs/Discord-Miaf-Shiona-Invite-Bot#1]
yarram gibi bot olmuş, benimkini atayım isterseniz 💋 💋 💋

**Comment by MiafJs** [comment]
Sellam canım nasılsın? Görüşmeyeli ... 😊😊

10 May 2021 Pzt 01:44 tarihinde Kürşat ***@***.***> şunu
yazdı:

**Comment by MiafJs** [comment]
> yarram gibi bot olmuş, benimkini atayım isterseniz 💋 💋 💋

**Comment by MiafJs** [comment]
> yarram gibi bot olmuş, benimkini atayım isterseniz 💋 💋 💋

Üzüyorsun ://
